from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

# Allow running this file directly without installing the package first.
PROJECT_ROOT = Path(__file__).resolve().parent
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from smart_scrape.config import Settings
from smart_scrape.qa.llm_client import LLMClientError
from smart_scrape.qa.llm_client import extract_deals_and_coupons_from_file
from smart_scrape.scraper.exceptions import (
    EmptyContentError,
    InvalidURLError,
    NavigationError,
    ScraperError,
)
from smart_scrape.scraper.playwright_client import scrape_page


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Scrape a URL with Scrapling, or upload a .txt file to Gemini for "
            "deals/coupons extraction."
        )
    )
    parser.add_argument(
        "url",
        nargs="?",
        help="URL to scrape, for example: https://apple.com",
    )
    parser.add_argument(
        "--save-html",
        default=None,
        help="Optional file path to write cleaned HTML output.",
    )
    parser.add_argument(
        "--save-text",
        default=None,
        help="Optional file path to write readable text output generated by html2text.",
    )
    parser.add_argument(
        "--input-text-file",
        default=None,
        help=(
            "Path to a .txt file that will be uploaded to Gemini for deals/coupon "
            "extraction."
        ),
    )
    parser.add_argument(
        "--save-deals",
        default="output/deals_and_coupons.txt",
        help="File path to write Gemini deals/coupons response text.",
    )
    parser.add_argument(
        "--gemini-model",
        default=None,
        help="Optional Gemini model override; defaults to GEMINI_MODEL.",
    )
    return parser.parse_args()


async def run(
    url: str,
    save_html: str | None,
    save_text: str | None,
    settings: Settings,
) -> int:
    result = await scrape_page(url=url, settings=settings)

    print(f"Requested URL: {result.requested_url}")
    print(f"Final URL: {result.final_url}")
    print(f"Title: {result.title or '(no title)'}")
    print(
        "Status Code: "
        f"{result.status_code if result.status_code is not None else 'unknown'}"
    )
    print(f"Cleaned HTML size: {len(result.cleaned_html)} characters")
    print(f"Readable text size: {len(result.cleaned_text)} characters")
    print(f"Elapsed: {result.elapsed_ms} ms")

    if save_html:
        output_path = Path(save_html).expanduser().resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(result.cleaned_html, encoding="utf-8")
        print(f"Saved cleaned HTML to: {output_path}")

    if save_text:
        output_path = Path(save_text).expanduser().resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(result.cleaned_text, encoding="utf-8")
        print(f"Saved readable text to: {output_path}")

    return 0


def run_gemini_deals_mode(
    settings: Settings,
    input_text_file: str,
    save_deals: str,
    gemini_model: str | None,
) -> int:
    model_name = gemini_model.strip() if gemini_model else settings.gemini_model

    response_text = extract_deals_and_coupons_from_file(
        input_text_file=Path(input_text_file),
        output_text_file=Path(save_deals),
        api_key=settings.gemini_api_key or "",
        model_name=model_name,
    )

    print(f"Input text file: {Path(input_text_file).expanduser().resolve()}")
    print(f"Gemini model: {model_name}")
    print(f"Deals response size: {len(response_text)} characters")
    print(f"Saved deals/coupons to: {Path(save_deals).expanduser().resolve()}")
    return 0


def main() -> int:
    args = parse_args()
    settings = Settings.from_env()

    if args.input_text_file:
        try:
            return run_gemini_deals_mode(
                settings=settings,
                input_text_file=args.input_text_file,
                save_deals=args.save_deals,
                gemini_model=args.gemini_model,
            )
        except LLMClientError as exc:
            print(f"Gemini extraction failed: {exc}", file=sys.stderr)
            return 6
        except OSError as exc:
            print(f"File operation failed: {exc}", file=sys.stderr)
            return 7

    url = args.url.strip() if args.url else input("Enter URL to scrape: ").strip()

    if not url:
        print("Error: URL is required.", file=sys.stderr)
        return 2

    try:
        return asyncio.run(
            run(
                url=url,
                save_html=args.save_html,
                save_text=args.save_text,
                settings=settings,
            )
        )
    except InvalidURLError as exc:
        print(f"Invalid URL: {exc}", file=sys.stderr)
        return 2
    except NavigationError as exc:
        print(f"Navigation failed: {exc}", file=sys.stderr)
        return 3
    except EmptyContentError as exc:
        print(f"No usable content: {exc}", file=sys.stderr)
        return 4
    except ScraperError as exc:
        print(f"Scraper error: {exc}", file=sys.stderr)
        return 5


if __name__ == "__main__":
    raise SystemExit(main())
